- docs/make.jl
- docs/src/examples/template_example.md
- docs/src/observations.md
- docs/src/parameter_distributions.md
Build documentation for several features of package:
- Prior distributions page
- Observations page
- Examples directory, Template example page
> [WIP] Documentation 

- docs/src/ensemble_kalman_sampler.md
"Problem Formulation" instead of "Problem Formulation and Ensemble Kalman Sampling Algorithm"
> Fix section title

- src/EnsembleKalmanProcess.jl
This PR fixes the scale of the error used in the EKI update, and adds a flag for deterministic vs stochastic model updates. 
The names of dimensionality of vectors are also updated to be consistent with the glossary.
> Fix EKI update, ensure consistency for stochastic models.

- docs/src/installation_instructions.md
- Add tagged version installation
- Fix instructions for building documentation
> Update installation instructions

- docs/src/ensemble_kalman_inversion.md
> Convert link in Ensemble Kalman Inversion documentation to relative url

- .dev/Project.toml
- .dev/clima_formatter_options.jl
- .dev/climaformat.jl
- .dev/hooks/pre-commit
- .github/workflows/JuliaFormatter.yml
- bors.toml
- docs/make.jl
- examples/ClimateMachine/helper_funcs.jl
- examples/ClimateMachine/init_calibration.jl
- examples/ClimateMachine/sstep_calibration.jl
- examples/Cloudy/Cloudy_example_eki.jl
- examples/Cloudy/Cloudy_example_uki.jl
- examples/Cloudy/DynamicalModel.jl
- examples/Lorenz/GModel.jl
- examples/Lorenz/Lorenz_example.jl
- examples/Lorenz/Lorenz_example_ukp.jl
- examples/LossMinimization/loss_minimization.jl
- src/DataStorage.jl
- src/EnsembleKalmanInversion.jl
- src/EnsembleKalmanProcess.jl
- src/EnsembleKalmanSampler.jl
- src/Observations.jl
- src/ParameterDistribution.jl
- src/UnscentedKalmanInversion.jl
- test/DataStorage/runtests.jl
- test/EnsembleKalmanProcessModule/runtests.jl
- test/Observations/runtests.jl
- test/ParameterDistribution/runtests.jl
- test/runtests.jl
Let's use the formatting that makes other CliMA packages look so nice.
> The great formatting.

- docs/src/parameter_distributions.md
This PR increases the line width in the Docs/Prior Distributions section. Also improves the code formatting and simplifies code a bit in the examples in this section.
> Docs/Prior Distributions section enhancements

- src/EnsembleKalmanInversion.jl
> More informative error message in `update_ensemble!`

- .github/workflows/Tests.yml
> remove nightly from test pipeline

- examples/SparseLossMinimization/loss_minimization_sparse_eki.jl
Regularize Sparse EKI example to avoid random failures.
> Fix Sparse EKI docs example

- src/DataContainers.jl
- test/DataContainers/runtests.jl
Resolves #114 
- deepcopy in `DataContainers` constructor
- tests to check copy on set and get.
> Add deepcopy to setting data

- Project.toml
This patch release closes issue #126 with PR #125 .
> Patch release v0.5.1, internal changes to Cholesky factorization of UKI.

- src/EnsembleKalmanProcess.jl
- Improves the default inflation factor used for singular covariance matrices. The inflation factor is now defined such that the corrected covariance matrix is well-conditioned with respect to a condition number of 1/sqrt(eps(FT)), which guarantees numerical positive definiteness.
> Improve default inflation when sampling singular covariance matrices.

- Project.toml
Release includes:
- Revamp of SparseInversion,
- Failsafe version of SparseInversion.
> Minor release v0.6

- docs/src/API/EnsembleKalmanProcesses.md
- src/EnsembleKalmanInversion.jl
- src/EnsembleKalmanProcess.jl
- src/EnsembleKalmanSampler.jl
- src/SparseEnsembleKalmanInversion.jl
- src/UnscentedKalmanInversion.jl
Improve docstrings for API documentation, adding struct fields and constructors.
> Improve docstrings for API documentation

- docs/src/index.md
Fixes a small typo in the docs.
> Small typo in docs

- docs/make.jl
- docs/src/contributing.md
This PR adds a contributing guide to the documentation, based on the guide in use for ClimateMachine.
> Add contributing guide.

- docs/src/ensemble_kalman_inversion.md
- docs/src/index.md
- docs/src/unscented_kalman_inversion.md
Document failsafe updates for ensemble and unscented Kalman Inversion.
Better documentation for users, no risks.
> Add failsafe update docs.

- docs/Project.toml
- examples/AerosolActivation/Project.toml
This PR fixes the CloudMicrophysics version in the documentation example, to avoid being affected by changes upstream.
> Fix CloudMicro version

- Project.toml
Make a new release with the newly added functionality and the most recent bug fixes.
> Bump to version v0.9.0

- Project.toml
- Patch release including cutoff localization kernel, and fix to Bernoulli kernel.
> Bump patch to 0.9.1

- docs/src/API/Localizers.md
- src/Localizers.jl
Improve API documentation for structs and functions in the Localizers module.
> Improve API docs for Localizers.

- test/EnsembleKalmanProcess/runtests.jl
Improves and expands the unit tests for EnsembleKalmanProcess algorithms.
- Regression tests are added to EKI and EKS,
- Dynamic type inference is reduced.
> Improve EKP testing

- docs/make.jl
- docs/src/API/EnsembleKalmanProcess.md
- docs/src/API/Inversion.md
- docs/src/API/Sampler.md
- docs/src/API/SparseInversion.md
- docs/src/API/Unscented.md
- docs/src/ensemble_kalman_inversion.md
- docs/src/index.md
- docs/src/unscented_kalman_inversion.md
- src/EnsembleKalmanInversion.jl
- src/EnsembleKalmanProcess.jl
- src/Localizers.jl
- src/SparseEnsembleKalmanInversion.jl
- src/UnscentedKalmanInversion.jl
Improves documentation by:
- Adding more functions to API and organizing different methods,
- Add lead developer names,
- Update citations,
- Tidy constructors, typos, etc.
> Improve and organize API, add lead developers, update citations.

- Project.toml
Bumps latest release to v0.10.0.
> Minor release v0.10.0

- docs/src/API/ParameterDistributions.md
- src/ParameterDistributions.jl
- Improve API documentation of ParameterDistributions.
> Improve ParameterDistribution API docs.

- Project.toml
> Update to v0.11

- docs/src/parameter_distributions.md
- src/DataContainers.jl
- src/ParameterDistributions.jl
- Improves ParameterDistribution docs.
- Removes unused kwarg from `combine_distributions`.
> Improve docs, remove unused kwarg.

- Project.toml
> Update to v0.13.0

- README.md
Add link to JOSS review process for easy and transparent tracking.
> Add JOSS badge for transparent review tracking

- Project.toml
> Update to v0.13.1

- docs/make.jl
Reorder docs to promote examples and tools, and push technical details further down
----
> Reorder docs pages

- src/EnsembleKalmanInversion.jl
- src/EnsembleKalmanProcess.jl
- src/EnsembleKalmanSampler.jl
- src/SparseEnsembleKalmanInversion.jl
- src/UnscentedKalmanInversion.jl
Use multiple dispatch on process-specific `update_ensemble!` calls, allowing a master `update_ensemble!` call to pass general keyword arguments.
> Use multiple dispatch on update_ensemble calls

- docs/src/parameter_distributions.md
Adds a simple `Samples` example into the docs
- created the `point_seven` example distribution using constrained and unconstrained samples in "Prior distributions" page
https://clima.github.io/EnsembleKalmanProcesses.jl/previews/PR240/parameter_distributions/#samples-example
----
> JOSS - new Samples examples

- paper.bib
- paper.md
Due to the JOSS submission: https://github.com/openjournals/joss-reviews/issues/4869#issuecomment-1336116300
- Correct bibtex (capitalization, etc.)
- Add missing references
- Correct paper
> update bibtex and paper

- Project.toml
> Update to v0.14.2

- Project.toml
> Update to v0.14.3

- docs/src/API/Inversion.md
- src/EnsembleKalmanInversion.jl
- src/EnsembleKalmanProcess.jl
- test/EnsembleKalmanProcess/runtests.jl
> removing find_ekp_stepsize

- Project.toml
> Update to v1.1

- Project.toml
> Update to v1.1.1

- Project.toml
> Update version 1.1.3

- Project.toml
> Update project to v1.1.4

- Project.toml
> Update to new [compat] requirements

- Project.toml
> Patch release can't reduce [compat]

- .github/workflows/Docs.yml
- .github/workflows/Tests.yml
> Handling bors removal: new workflows 

- Project.toml
> Update Project.toml to v1.1.5

- Project.toml
> Update version to v1.1.6

- README.md
- docs/src/API/EnsembleKalmanProcess.md
- docs/src/index.md
- docs/src/troubleshooting.md
- examples/Cloudy/Cloudy_example_uki.jl
- examples/LearningRateSchedulers/compare_schedulers.jl
- examples/LearningRateSchedulers/compare_schedulers_uki.jl
- examples/Localization/localization_example_lorenz96.jl
- examples/Lorenz/Lorenz_example_ukp.jl
- src/Accelerators.jl
- src/EnsembleKalmanInversion.jl
- src/EnsembleKalmanProcess.jl
- src/EnsembleKalmanSampler.jl
- src/EnsembleTransformKalmanInversion.jl
- src/FunctionParameterDistributions.jl
- src/LearningRateSchedulers.jl
- src/ParameterDistributions.jl
- src/SparseEnsembleKalmanInversion.jl
- src/UnscentedKalmanInversion.jl
- test/EnsembleKalmanProcess/runtests.jl
- test/Localizers/runtests.jl
- test/ParameterDistributions/runtests.jl
- test/SparseInversion/runtests.jl
Before the breaking release of `v2.0.0` we will resolve some outstanding interface issues.
Closes #369 
Closes #381 
Address several points in #386
- add getters to cover EKP internals, add API docs and testing, use getters consistently through code
- resolve the `transform_unconstrained_to_constrained` and it's inverse for numbers, vector and misshapen array input
- rename `ekp.err` as `ekp.error`
- add return_array to `get_\phi` etc.
- change the confusing `get_localizer` in EKP to `get_localizer_type` and add `get_localizer` to return the actual localizer
- consistent getter use in examples
- New quick link in Readme/docs
----
> Miscellaneous interface changes, solving several older issues

- Project.toml
> Update Project.toml to v2.0.0 breaking

- src/EnsembleKalmanInversion.jl
Closes #399 
patch release coming to resolve this...
----
> remove warning for now on Accelerator vs deterministic_forward_map

- .github/workflows/DocPreviewCleanup.yml
- .github/workflows/Docs.yml
- .github/workflows/JuliaFormatter.yml
- .github/workflows/Tests.yml
> Combine Dependabot PRs

- src/EnsembleTransformKalmanInversion.jl
Bugfix to bug introduced in PR #380,
----
> Bugfix a lost Delta t scaling for ETKI

- Project.toml
> Update Project.toml to v2.1.0

- docs/src/API/EnsembleKalmanProcess.md
- src/EnsembleKalmanProcess.jl
- test/UpdateGroup/runtests.jl
Closes #457 
- bugfix u_group logic
- unit test for the code with more-than-one minibatch
----
> [WIP] bugfix u_idx for minibatch + parameter_groups

- Project.toml
> Update Project.toml to v2.2.0

- Project.toml
> Update Project.toml V2.3.1

- docs/src/API/Observations.md
- docs/src/observations.md
- src/Observations.jl
- test/EnsembleKalmanProcess/runtests.jl
- test/Observations/runtests.jl
Closes #474
- can a `lmul_sqrt` method be created for such types? [Not yet implemented- note also not necessary for the EKP algorithms]
- Introduce the new matrix storage options `SVDplusD` (to store a covariance compactly) and `DminusTall` (to store the inverse of `SVDplusD` compactly.
- On construction of `ObservationSeries` the `SVDplusD` object is correctly inverted, and inverse stored as a `DminusTall`
- correctness of the lmul function and scalability checked with unit tests
- Documentation! See [here](https://clima.github.io/EnsembleKalmanProcesses.jl/previews/PR473/observations/)
```
using EnsembleKalmanProcesses, LinearAlgebra
n=100                                      # dim of observation
Γ_diag = Diagonal( 0.01*collect(1.0:n))    # diagonal noise
Z = randn(n, 5) …
```
> SVDplusD, for representing a covariance as a sum of SVD and Diagonal without building it

- Project.toml
> Update Project.toml to v2.4.0

- Project.toml
> Update Project.toml to v2.4.2

- src/Observations.jl
- test/Observations/runtests.jl
- bugfix strings being converted to long character strings under `append!`
- used in docs page
----
> Bugfix string metadata being made into Chars

- Project.toml
> Update Project.toml to v2.5.0

- docs/src/ensemble_kalman_sampler.md
- docs/src/unscented_kalman_inversion.md
- New EKS figures load in local docs build but not global: (due to _online-only_ figures linking to `dev/ensemble_kalman_sampler/assets/` and not `dev/assets/` 
- correct linking
- add new note about passing in "prior, impose_prior=true" to UKI as the recommendation
----
> bugfix docs image link
