Project.toml, src/DataStorage.jl, src/EnsembleKalmanProcess.jl, src/EnsembleKalmanProcesses.jl, src/Observations.jl, src/ParameterDistribution.jl, test/DataStorage/runtests.jl, test/EnsembleKalmanProcessModule/runtests.jl, test/Observations/runtests.jl, test/ParameterDistribution/runtests.jl, test/runtests.jl
Resolves some of #1 
We move the following modules from CES
- `EnsembleKalmanProcesses`, renamed `EnsembleKalmanProcessModule` (for obvious name clash)
- `Observations`
- `DataStorage`
- `ParameterDistributionStorage`
I also have moved over all unit tests for these modules. and updated the Project toml
=> Initial move of source files and runtests from CalibrateEmulateSample

.github/codecov.yml
Disable PR comments in favor of less noisy GH status checks
=> Adjust codecov to not fail when coverage drops < 10%

docs/src/installation_instructions.md, examples/LossMinimization/loss_minimization.jl, src/ParameterDistribution.jl, test/EnsembleKalmanProcessModule/runtests.jl, test/ParameterDistribution/runtests.jl
The current output of get_mean(ParameterDistribution) is an `Array{FT, 2}` that cannot be used as an input to the `Sampler()`. I did not see any instance of the code where this structure was useful, so I have changed the function to return an `Array{FT, 1}`. 
Note that this change simplifies every single use of get_mean(ParameterDistribution) in the tests and examples.
Apart from this, I have corrected the installation guide.
=> Fix get_mean() for PDs, fix installation docs

src/EnsembleKalmanProcess.jl, test/EnsembleKalmanProcessModule/runtests.jl
This PR simplifies substantially the update of the EKI algorithm.
- The computation of the cross-covariance matrices was done through a loop, which is unnecessary since we are already loading the Statistics module.
- Everything was transposed for some reason. Now all data are stored in columns, similarly to the rest of the code.
The new construction produces the same results (tested with an `assert` before this PR). Note that I have not added the Bessel correction to the cross-covariances `cov_ug` and `cov_gg` to ensure consistency with the papers and the previous version. We can discuss this.
In addition, I have fixed an issue with the construction of `y`, which was `Array{FT,1}` for `!deterministic_forward_map`.
=> Simplify EKI update, correct dims error in nondeterministic settings

src/ParameterDistribution.jl
text should be `no_constraint()` instead of `NoConstraint()`.
=> fix: no constraint error message

docs/make.jl, docs/src/unscented_kalman_inversion.md
This PR adds documentation for the unscented Kalman sampler
=> Add documentation for unscented Kalman inversion

src/Observations.jl, test/Observations/runtests.jl
Fixes #34 by 
- changing the assert 
- also prevents `obs_noise_cov` modifications in `Observations`,
- added runtests for the scalar noise case (and the other edge cases too)
=> removed unsatisfiable assert, stopped overwriting of obs_noise_cov

docs/src/ensemble_kalman_inversion.md
=> Clarifies notation and units in Ensemble Kalman Inversion documentation

docs/src/parameter_distributions.md
Resolves #44 
Check out the parameter distributions section in the documentation
TODO:
=> initial gifs for priors

Project.toml
The Distributions package pinned previously was incompatible with the new TC.jl environment.
=> unpin Distributions version

.github/workflows/CompatHelper.yml
Add the CompatHelper workflow to keep dependencies up to date, as we do in other CliMA packages.
=> Add CompatHelper workflow.

src/ParameterDistribution.jl, test/ParameterDistribution/runtests.jl
This PR adds additional element-wise parameter transformers that can take structures such as `Array{FT,2}` or `Array{Array{<:Real,2},1}`, often encountered in the parameter calibration process.
=> Add parameter transformers for additional structures.

src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcessModule/runtests.jl
This PR cleans up some unused calls and inputs in the Unscented Kalman constructor. Behavior is unchanged, except for the call to `Unscented`, which now has one argument less.
=> Remove unnecessary calls and inputs in UKI.

src/DataStorage.jl, src/EnsembleKalmanInversion.jl, src/EnsembleKalmanProcess.jl, src/EnsembleKalmanProcesses.jl, src/EnsembleKalmanSampler.jl, src/Observations.jl, src/ParameterDistribution.jl, src/UnscentedKalmanInversion.jl
This PR adds code formatting in some docstrings (e.g., adds encloses code name variables in backticks) to allow better rendering in the Docs/API. This way a variable named `long_name` does not appear as: long _name_.
=> Better code format in docstrings to allow better rendering in Docs/API

docs/src/ensemble_kalman_inversion.md, docs/src/ensemble_kalman_sampler.md, docs/src/glossary.md, docs/src/index.md, docs/src/observations.md, docs/src/parameter_distributions.md, docs/src/unscented_kalman_inversion.md
This PR fixes some typos + punctuation in the docs and enhances the code formatting in the inline examples provided in the docs.
=> Fix typos and code formatting in Docs

.github/workflows/DocPreviewCleanup.yml
based on https://github.com/CliMA/TimeMachine.jl/blob/master/.github/workflows/DocCleanup.yml
=> Create GitHub action that cleans up the Docs preview versions from PRs

Project.toml
This PR generalizes a bit the compatibility requirements of the various dependencies.
In particular, the PR will allow the use of the patch releases: DocStringExtensions v0.8.5, Distributions v0.25.18, and StatsBase.jl v0.33.11.
=> Generalize deps compat requirements

src/DataStorage.jl
Resolves #71, when we load data from data storage we should always copy, as it is history and should not be overwritable
I was recently stung by the old mutability vs assignment:
```julia 
x=ones(10)
f() = return x
```
then 
```julia 
u1 =  f()
u1 += ones(10)
```
and
```julia 
u2 = f()
u2 = 2*ones(10)
```
But(!)
```julia 
u3 = f()
u3[:] = 2*ones(10)
```
let's not rely on people like me to remember this in e.g. the getters from storage `get_u`,`get_u_final`,`get_u_prior` etc.
A copy in the `get_data` method of the `DataStorage` class resolves this
```julia 
x=ones(10)
g() = return copy(x)
u4 = g()
u4[:] = 2*ones(10)
```
=> added a copy

docs/src/parameter_distributions.md, src/UnscentedKalmanInversion.jl
The initialization of the mean in UKI need not be the prior mean. In some situations, we may want to reconstruct the EnsembleKalmanProcess after every iteration, conserving the same prior. The current constructor did not allow this; it selected the current mean as the prior mean. This PR decouples the two, without changing the default behavior of the system.
In addition, comments and typing are improved for the module.
=> Decouple initial conditions in UKI from prior for regularization.

src/EnsembleKalmanSampler.jl, test/EnsembleKalmanProcessModule/runtests.jl
To get the EKI runtest properly working with a linear map from R^{2} -> R^{10}. (i) some reason a couple of the `@test` statements were commented out (ii) the tests comparing EKS and EKI are very dependent on N_iter
Changes to the EKI test in `test/EnsembleKalmanInversion/runtests.jl` So that it now converges reasonably and satisfies all the test conditions. 
NB some of the comparisons of eks/eki depended heavily on `N_iter`. To compare the two algorithms we should really look at the timesteps in absolute time. So now
1. I have increased the prior strength and bias
1. I run EKS first with it's adaptive timestep, which I store in `eksobj`
2.  then use these values in the EKI updates. 
The OLS mean is nearer the EKI at the end time, and the posterior mean is nearer the EKS at the end time, …
=> modified EKI/EKS runtest

.github/workflows/Docs.yml, .github/workflows/JuliaFormatter.yml, .github/workflows/Tests.yml
This PR changes the GitHub Actions workflows to use Julia v1.6.4 which is the new long-term support version.
Now the docs are being built with Julia v1.6.4 and the test run on v1.6.4 and on v1.7.
Closes #79
=> Update GitHub Actions workflows to use Julia 1.6.4

docs/src/unscented_kalman_inversion.md, examples/Cloudy/Cloudy_example_uki.jl, examples/Lorenz/Lorenz_example_ukp.jl, src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcessModule/runtests.jl
The UKI constructor modification
```
function Unscented(
u0_mean::Vector{FT},
uu0_cov::Matrix{FT};
α_reg::FT = 1.0,
update_freq::IT = 1,
modified_unscented_transform::Bool = true,
prior_mean::Union{Vector{FT}, Nothing} = nothing,
) where {FT <: AbstractFloat, IT <: Int}
```
require α_reg, update_freq, modified_unscented_transform, and  prior_mean as keyword arguments
clean up κ and β.
=> Standardize UKI constructor to be consistent with EKS, document kwargs 

src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcessModule/runtests.jl
Adds the possibility to perform quadratures over scalars in UKI, and vectorizes some computations.
It also enables the use of `construct_cov()` directly without passing the mean. However, the default behavior is unchanged.
=> Allow quadrature of scalar metrics in UKI, vectorize mean quadrature.

Project.toml, src/EnsembleKalmanInversion.jl, src/EnsembleKalmanProcess.jl, src/EnsembleKalmanSampler.jl, src/ParameterDistributions.jl, src/SparseEnsembleKalmanInversion.jl, src/UnscentedKalmanInversion.jl, test/DataContainers/runtests.jl, test/EnsembleKalmanProcess/runtests.jl, test/ParameterDistributions/runtests.jl
This is a rebase and squash of the feature branch for PR #81 and contains no new commits. The PR message for #81 is reproduced below.
<hr>
The motivation for this PR comes from CliMA/CalibrateEmulateSample.jl#121; see discussion there. 
In order to have reproducible tests involving randomness, it's not sufficient to set the global seed for the default RNG: the default RNG algorithm used by Julia was [changed](https://julialang.org/blog/2021/11/julia-1.7-highlights/#new_rng_reproducible_rng_in_tasks) in version 1.7, and the [docs](https://docs.julialang.org/en/v1/stdlib/Random/#Reproducibility) for the Random package note that the same seed may give different random values in different versions. For this reason, [recommended practice](https://discourse.julialang.org/t/set-the-state-of-the-g …
=> Pass explicit RNG object to methods involving stochasticity

Project.toml, docs/src/API/ParameterDistributions.md, docs/src/ensemble_kalman_sampler.md, docs/src/parameter_distributions.md, src/DataContainers.jl, src/EnsembleKalmanProcess.jl, src/ParameterDistributions.jl, test/EnsembleKalmanProcess/runtests.jl, test/ParameterDistributions/runtests.jl
To replace some functions with corresponding extensions from existing packages. (and the relevant tests/examples)
resolves #92 
- ParameterDistributions: By extending from `StatsBase`. Replacing `get_mean` `get_var` `get_cov` 'sample_distribution' by extending `mean` `var` `cov` `sample` 
- ParameterDistributions: by extending `Base`: Change `len` to `length`, added `size`, change `dimension`and `get_total_dimension` to `ndims`
=> Extending functions from packges

src/DataContainers.jl, src/EnsembleKalmanInversion.jl, src/EnsembleKalmanProcess.jl, src/EnsembleKalmanSampler.jl, src/Observations.jl, src/ParameterDistributions.jl, src/SparseEnsembleKalmanInversion.jl, src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl
Relaxes the allowed types of some objects and input args for improved generalization:
- Vector - > AbstractVector
- Matrix -> AbstractMatrix
- Sparse.SparseMatrix -> AbstractMatrix
- Union{Vector, Matrix} -> AbstractVecOrMat
For covariance matrices in output space,
- Matrix -> Union{AbstractMatrix, UniformScaling}
Tests involving different matrix types are now included for all Ensemble Kalman Processes.
=> Substitute types by abstractions.

src/EnsembleKalmanProcess.jl, test/EnsembleKalmanProcess/runtests.jl
Fixes CliMA/EnsembleKalmanProcesses.jl#104.
This PR corrects the logic for construct_initial_ensemble() to the following:
1. If an rng is not passed as the first argument, GLOBAL_RNG is used (same convention as StatsBase, Random, etc.)
2. If and only if a value for `rng_seed` is given, the rng is re-seeded to that value.
Previously, passing both `rng_seed` and `rng` as optional kwargs to  meant that, if neither was supplied, GLOBAL_RNG was re-seeded to 42 on every call.
Add @ilopezgp's MWE from #104 to the unit tests as a sanity check.
=> Correct rng kwargs for construct_initial_ensemble()

src/EnsembleKalmanInversion.jl, src/EnsembleKalmanProcess.jl, src/SparseEnsembleKalmanInversion.jl, src/UnscentedKalmanInversion.jl
Adds the continuous version of UKI dynamics as specified in Huang et al (2021), section 3.4,
Σ_ω -> Σ_ω * Δt
Σ_ν -> Σ_ν / Δt
I didn't change alpha to alpha_h, I think that's fine from the paper.
Also moves the dt constructor to EnsembleKalmanProcess.jl.
=> Add continuous UKI dynamics discretization.

Project.toml, src/EnsembleKalmanInversion.jl, src/EnsembleKalmanProcess.jl, src/EnsembleKalmanSampler.jl, src/SparseEnsembleKalmanInversion.jl, src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl
- Adds a failure handler struct to all `EnsembleKalmanProcess` objects.
- Implements the `IgnoreFailures` failure handler for all `EnsembleKalmanProcess`es, which maintains the former behavior of the algorithms (i.e, do nothing upon failure).
- Implements the `SampleSuccGauss` failure handler for the Inversion process, which advances the failed ensemble by sampling from an empirical gaussian formed by the successful ensemble.
- Failure may be defined by the user by passing the indices of failed particles to `update_ensemble!`. If nothing is passed, failures are taken to be those forward model evaluations that contain NaNs.
- Adds tests of new failure handlers.
In addition:
- Update equations are encapsulated outside of `update_ensemble!`, and into functions `..._update`.
- Transposes in …
=> Add failsafe EKI with sample_succ_gauss handler.

src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl
Adds the Sample-successful-gaussian Failure Handler for the Unscented Kalman Inversion.
The handler is applied during the analysis step, by computing the ill-defined means and covariances over the successful particles. In order to preserve the sum of the weighting scheme, the weights at each successful sigma point are scaled up.
Consider a set of sigma points {θ_j}={θ_succ_j} U {θ_fail_j}, from which we have to estimate E[G], Cov(G, G) and Cov(G, θ) for the UI update rules. These would generally be computed through the quadrature rules of UKI (possibly modified following Huang et al 2021).
For the mean of the forward model eval we do:
- E[G] ≈ ∑_succ [(∑W_j) / (∑_succ W_j) * W_j * G(θ_succ_j)] if the center particle did not fail (rescaled quadrature).
- E[G] ≈ ∑_succ G(θ_succ_j) / …
=> Adds SampleSuccGauss FailureHandler for UKI

Project.toml
- Bumps version to 0.4 after the addition of FailureHandlers for Inversion and Unscented KalmanProcesses.
=> Bump version to v0.4.

src/SparseEnsembleKalmanInversion.jl
The purposes of this pull request are:
- Update the implementation of sparse EKI to make it compatible with the new version of DataContainer.
=> Address issue #113

src/EnsembleKalmanInversion.jl, src/EnsembleKalmanSampler.jl, src/SparseEnsembleKalmanInversion.jl, src/UnscentedKalmanInversion.jl
Homogenizes the use of kwargs in the `update_ensemble!` call across Processes. The only two args are the EKP object and the forward model evaluations. The rest of the inputs are taken as kwargs.
=> Homogenize update_ensemble! kwargs.

src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl
Update the Cholesky factor computation in UKI
When the matrix is not positive definite, compute SVD of the matrix, replace 0 singular values as the smallest nonzero singular value (with a threshold 1e-8), and then compute the Cholesky factor.
=> update cholesky in UKI

examples/SparseLossMinimization/loss_minimization_sparse_eki.jl, src/SparseEnsembleKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl
- Removes `threshold_eki` boolean, since it can be inferred from magnitude of `threshold_value`.
- Sets `reg` last, since it is a parameter only needed for numerical stability and ideally not user-facing. 
-  Verifies that `reg` is positive definite before attempting to sample from a gaussian with `reg` as its variance.
- Adds base kwarg constructor to SparseInversion.
- Adds defaults to struct properties and an outer constructor that accepts a flexible number of keyword parameters.
=> Simplify SparseInversion struct, add more constructors.

src/EnsembleKalmanInversion.jl, src/EnsembleKalmanProcess.jl, src/SparseEnsembleKalmanInversion.jl, src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl
Adds localization kernels to EKI, UKI and SparseEKI following the localization of the empirical cross-covariance as suggested by Tong and Morzfeld (2022).
Three localization kernels are implemented: The NoLocalization kernel, the Delta kernel and the RBF kernel. Kernels are built at EKP construction time and stored in the struct.
=> Add localization kernels.

docs/src/API/Localizers.md, src/EnsembleKalmanProcess.jl, src/EnsembleKalmanProcesses.jl, src/Localizers.jl, test/EnsembleKalmanProcess/runtests.jl, test/Localizers/runtests.jl, test/runtests.jl
This PR:
- Organizes the Localizers as a new module of the package, to declutter `EnsembleKalmanProcess.jl`,
- Literates docstrings describing non-evident localizer kernels,
- Adds a new Localizer that drops correlations as Bernoulli trials, based on the notion of Dropout in deep learning.
=> Organize localizers into module, add randomized localizer

src/EnsembleKalmanProcess.jl
The current condition seemed to not be met in situations were `checkposdef(cov)=false`. We modify the condition to align with the check by using `isposdef()`.
=> Improve precision of positive definiteness in sampling

docs/src/installation_instructions.md, examples/Lorenz/Project.toml, examples/LossMinimization/Project.toml, examples/SparseLossMinimization/Project.toml
To add `Project.toml` files for `LossMinimization`, `SparseLossMinimization` and updates `Lorenz`, also adds some docs for running the examples
Fixes #171
- Examples can now run immediately after instantiation.
- Users now have docs to tell them how to instantiate examples and run them.
- Project tomls increase consistent behavior.
=> Add Project tomls and EKP dep for examples,

src/EnsembleKalmanProcess.jl
- Fixes #170 by casting the covariance to Symmetric, which should avoid complex eigenvalues due to discrete precision arithmetic.
=> Cast empirical covariance to symmetric.

examples/Localization/localization_example_lorenz96.jl, src/Localizers.jl
Randomizes the Bernoulli kernel at every iteration of the EKP. The current version generated a single kernel matrix and used it throughout the inversion process.
=> Randomize Bernoulli kernel at every iteration

examples/Localization/localization_example_lorenz96.jl, src/Localizers.jl, test/Localizers/runtests.jl
Adds the option to apply a cutoff below which SEC-corrected covariances are set to 0, sparsifying the covariance matrix. This follows the logic of kernels used in data assimilation which have a compact support, like the Gaspari-Cohn function.
Explore the usefulness of correlation sparseness, addition of a novel localization function (not used yet in the literature?). So far it is looking good! (See plot below).
=> Add cutoff to SEC localizer

examples/Lorenz/Lorenz_example_ukp.jl, src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl
In this PR, we add an argument for Unscented struct and its constructor
The number of sigma points (ensemble size) N_ens can be  = 2N+1 or N+2
In its constructor, the default value is 2N+1
=> add N_ens input to Unscented, it can be N+2 or 2N+1

.github/workflows/Tests.yml
The unit tests do not work yet with Julia 1.8. The CI is fixed to the 1.6+1.7.3 versions until the issues with Julia 1.8.0 are resolved.
=> Fixes CI to Julia 1.7.3, tests not yet working for 1.8

docs/make.jl, docs/src/localization.md
- Document localization kernels.
=> Add localization documentation.

src/EnsembleKalmanInversion.jl, src/EnsembleKalmanSampler.jl, src/ParameterDistributions.jl, src/SparseEnsembleKalmanInversion.jl
Unlinks the type of real inputs to ParameterDistributions functions, allowing the use of `Int`s and infinites.
- Closes #185
=> Unlink real inputs in ParameterDistributions.

docs/src/API/ParameterDistributions.md, src/ParameterDistributions.jl, test/DataContainers/runtests.jl, test/ParameterDistributions/runtests.jl
Fixes #184 and #192, also small update to remove warning in DataContainers/ParameterDistributions test. This works towards a better interface for ParameterDistributions. 
- Extending `constrained_gaussian` to multidimensional distirbutions by adding a `repeats=N` keyword with `N=1` default.
- Adds Types constraints into `NoConstraint` `BoundedBelow` `BoundedAbove` and `Bounded`
- Adds "parameters" to constraints, containing a Dict (or nothing). allows extraction of values of interest. for example 
`x = bounded_below(3.0)`  stores  `x.parameters = Dict("lower_bound" => 3.0)`
- extending `==` to Constraints (based on the above `parameters` and `Types`, as constraints are functions so hard to equate) 
- extending `==` to ParameterDistributions for easier testing calls
- Miscellaneous: …
=> ParameterDistributions.jl improvements

test/EnsembleKalmanProcess/inverse_problem.jl, test/EnsembleKalmanProcess/runtests.jl, test/SparseInversion/runtests.jl, test/runtests.jl
Major refactoring of EKP unit tests.
- Separate inverse problem definition from tests. Inverse problem definition moved to different file for readability and portability.
- Include nonlinear inverse problem test for EKI, EKS, UKI.
- Fix UKI test, which before used perfect denoised samples.
- Separate SparseEKI into a different file, and modify the test to make it much easier to pass.
=> Refactor EKP tests

.github/workflows/Tests.yml, src/EnsembleKalmanInversion.jl
Update package to be compatible with Julia v1.8. Compatibility does not seem to be automatic, since our tests are not passing.
=> Test on latest Julia version (~1.8)

docs/src/contributing.md, docs/src/ensemble_kalman_inversion.md, docs/src/ensemble_kalman_sampler.md, docs/src/examples/template_example.md, docs/src/glossary.md, docs/src/index.md, docs/src/parameter_distributions.md, docs/src/unscented_kalman_inversion.md
To clean-up the documentation. Closes #190 
[SHORTCUT TO DOCS](https://clima.github.io/EnsembleKalmanProcesses.jl/previews/PR207/)
- Updated links with DOIs
- Unified and trimmed Docs for the methods sections. Particularly UKI.
- Added a small SEKI section in EKI
- New getter functions, and clarification note for `u`, ``\phi`` and ``\theta`` notations
=> first pass for docs improvements

docs/src/ensemble_kalman_inversion.md, src/DataContainers.jl, src/EnsembleKalmanSampler.jl, src/ParameterDistributions.jl, src/SparseEnsembleKalmanInversion.jl, src/UQParameters.jl, src/UnscentedKalmanInversion.jl, test/UQParameters/runtests.jl, test/UQParameters/toml/bad_param.toml, test/UQParameters/toml/uq_test_parameters.toml
Closes #199, and improved error messaging.
- Adds information such as "Expected `X`, got `Y` " where applicable into the error messages
- Changes `error(` and `ErrorException` to better errors where required.
- Improves codecov for error messages 
- Also, adds a one-character bugfix ([`\!!! info` -> `!!! info`](https://clima.github.io/EnsembleKalmanProcesses.jl/dev/ensemble_kalman_inversion/#Handling-forward-model-failures)) in a docs page, updated version [here](https://clima.github.io/EnsembleKalmanProcesses.jl/previews/PR209/ensemble_kalman_inversion/#Handling-forward-model-failures) (not worth a separate PR)
=> Improved error messaging

docs/src/examples/Cloudy_example.md, docs/src/examples/lorenz_example.md, docs/src/parameter_distributions.md, examples/AerosolActivation/Project.toml, examples/AerosolActivation/aerosol_activation.jl, examples/ClimateMachine/init_calibration.jl, examples/Cloudy/Cloudy_example_eki.jl, examples/Cloudy/Cloudy_example_uki.jl, examples/Localization/localization_example_lorenz96.jl, examples/Lorenz/Lorenz_example.jl, examples/Lorenz/Lorenz_example_ukp.jl, examples/Lorenz/distributed_Lorenz_example.jl, examples/LossMinimization/loss_minimization.jl, examples/SparseLossMinimization/loss_minimization_sparse_eki.jl
To run through all current EKP examples, checking they run, checking whether manifests could be updated, and applying our new code-styles and interfaces. 
Checked and updated examples and docs for:
=> Updating and checking EKP examples

src/EnsembleKalmanSampler.jl, src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl
Unifies the constructors with the new prior interfaces. for examples users will not have to calculate means or covariances in computational space of the prior for to build `Unscented` or `Sampler` objects. instead we pass the `prior`.
- new (additional) constructors for `Unscented` and `Sampler` objects
- unit tests
- Closes #212
=> new tests and constructors

src/ParameterDistributions.jl, test/ParameterDistributions/runtests.jl
Closes #223 
Note the optimization appears more robust now for no loss of accuracy (according to our unit testing)
- Set ICs in unconstrained space to (0,1) rather than trying to get a more intelligent approximation
- removed tests for IC function
=> Revert to stable ICs for `constrained_gaussian` solver

Project.toml
Breaking release of EKP.jl following changes in module naming conventions.
=> Update version of EKP.jl to post-review status.

src/ParameterDistributions.jl, test/ParameterDistributions/runtests.jl
Closes #248 , by providing convenience methods to deal with the results of `get_distribution(Samples(...))`  
- add new `transform_unconstrained_to_constrained` for dicts
- add new `transform_constrained_to_unconstrained` for dicts
- add `get_all_constraints` with `return_dict` flag
- add `Samples`-based `ParameterDistribution` constructor from `AbstractMatrix` input
- add unit tests
----
=> Add dict-based transforms

docs/src/parameter_distributions.md, test/ParameterDistributions/runtests.jl
Closes #256 
Closes #255 
- Added more accessible `using` statements to begin snippets that are likely to be copy+pasted by readers
- Added what is brought in with `using` statements
- bugfix example
- resolved some tests fail on Julia `1` testing (here, `1.8.5`), due to updates  (bugs) in global rng / Distributions
Docs page [here](https://clima.github.io/EnsembleKalmanProcesses.jl/previews/PR258/parameter_distributions/)
----
=> Improve docs snippets in prior distributions page

src/ParameterDistributions.jl
See #257 for details.
With this implementation, combining all the examples [here](https://clima.github.io/EnsembleKalmanProcesses.jl/dev/parameter_distributions/#ParameterDistribution-constructor) gives a vector that displays like this:
```julia
julia> combine_distributions([u; prior])
ParameterDistribution with 7 entries: 
'constrained_mvnormal' with Constraint[Bounds: (0, ∞), Bounds: (0, ∞), Bounds: (0, ∞)] over distribution Parameterized(FullNormal( dim: 3 μ: [1.0, 1.0, 1.0] Σ: [0.5 0.25 0.0; 0.25 0.5 0.25; 0.0 0.25 0.5] ) ) 
'constrained_sampled' with Constraint[Bounds: (10, 15), Bounds: (-∞, ∞)] over distribution Samples{Float64}([1.0 5.0 9.0 13.0; 3.0 7.0 11.0 15.0]) 
'Beta' with Constraint[Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: (-∞, ∞), Bounds: …
```
=> implement Base.show for core types

Project.toml, docs/src/parameter_distributions.md, src/EnsembleKalmanProcesses.jl, src/PlotRecipes.jl, test/PlotRecipes/runtests.jl, test/runtests.jl
Closes #254
- For the wide variety of possible distributions, the easiest general solution is to plot marginal histograms of distributions, so this is the approach we take.
- Adds recipe for `plot(pd::ParameterDistribution)` 
- Adds recipe for `plot(pd <: ParameterDistributionType)` 
- Adds unit test which plots marginals (set `ENV["CES_TEST_PLOT_OUTPUT"] = true` prior to `] test`)
- Adds example into the priors docs page.
I expect these can be improved upon in various ways, using other plot-types, or only plotting unique distributions where they are repeated etc. but for this PR I just wanted something simple to work on any case.
A complicated distribution: 
```julia
d1 = Parameterized(MvNormal(zeros(4), 0.1 * I))
c1 = [no_constraint(), bounded_below(-1.0), bounded_above(0.4), …
```
=> Quickly plot marginals for parameter distribution

src/ParameterDistributions.jl, test/EnsembleKalmanProcess/runtests.jl, test/Inflation/runtests.jl, test/ParameterDistributions/runtests.jl
- Closes #265 
- Addresses #261 (1/2)
Leads to a more robust test pipeline and constructor `constrained_gaussian`
- fixes bugs within #265 ,
- resolves an eks object bug where it would mix prior and final ensemble, and now puts plots in the EKP test subdirectory
- adds warning for when users prescribe values in `constrained_gaussian` which will be slow to solve. In these cases a large amount of mass will be concentrated on the boundary.
- tightens error of termination to `mu + sig < upper_bound`  (before was `mu + 0.7*sig > 1` etc.) likewise for lower bound
----
=> Small bug fixes in tests

src/EnsembleKalmanInversion.jl, src/EnsembleKalmanProcess.jl, src/EnsembleKalmanSampler.jl, src/SparseEnsembleKalmanInversion.jl, src/UnscentedKalmanInversion.jl
=> Diagnostics

.github/workflows/Docs.yml, .github/workflows/JuliaFormatter.yml, src/EnsembleKalmanProcess.jl, src/FunctionParameterDistributions.jl, src/ParameterDistributions.jl, src/TOMLInterface.jl, src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl, test/TOMLInterface/runtests.jl
- Adds >=v1.9 tests where behaviour changes. 
Changes weres isolated to Failure handler tests, as the most up-to-date `LinearAlgebra` no longer allows as much propagation of NaNs, rather it throws errors. (I think this is a good idea)
- Removes the various precompile warnings about "FT defined but not used" 
- Removes the precompile warning of a clash in `sample` by now importing `GaussianRandomFields` rather that using it. This is (I think) because GRF.jl does not extend the StatsBase sample function, and we cant `import StatsBase: sample` AND `using GaussianRandomFields` without warnings.
- Update github workflows for docs and formatter to include `v1.X` from pinning to `1.7` 
----
=> Fix v1.9.0 testing

examples/AerosolActivation/aerosol_activation.jl, examples/Cloudy/Cloudy_example_eki.jl, examples/Darcy/calibrate.jl, examples/Lorenz/Lorenz_example.jl, examples/Lorenz/distributed_Lorenz_example.jl, examples/LossMinimization/loss_minimization.jl, examples/SparseLossMinimization/loss_minimization_sparse_eki.jl, examples/example_template.jl, src/EnsembleKalmanProcess.jl, test/EnsembleKalmanProcess/runtests.jl
Closes #260 
Pass RNG  objects instead of seeds to make randomness more traceable.
=> pass RNG instead of seeds

docs/src/learning_rate_scheduler.md, src/LearningRateSchedulers.jl, test/EnsembleKalmanProcess/runtests.jl, test/SparseInversion/runtests.jl
Closes #290 
- Added a keyword argument `terminate_at` for DMC
- Added tests to show it stops at the correct time
- Added a line into the docs 
----
=> Allow users to select termination time for DataMisfitController

docs/src/parameter_distributions.md
Closes #226 
- Adds a note about defining mean/variances too close to a boundary
- Adds a `repeats=3` keyword argument to the example to demonstrate this feature. 
See changed docs [here](https://clima.github.io/EnsembleKalmanProcesses.jl/previews/PR293/parameter_distributions/#constrained-gaussian).
----
=> Recommended Constructor Docs update

src/LearningRateSchedulers.jl, test/EnsembleKalmanProcess/runtests.jl
Closes #292 
- added successful_ens filter to calculations of delta t
- added the `DataMisfitController()` into a test case which contains particle failures and it no longer breaks
----
=> Schedulers no longer break when particle failures occur

src/LearningRateSchedulers.jl, test/EnsembleKalmanProcess/runtests.jl
Closes #297 
- add overload to `Base.(==)` for `LearningRateSchedulers`
- add tests
----
=> Add == for schedulers

docs/src/unscented_kalman_inversion.md, src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcess/inverse_problem.jl, test/EnsembleKalmanProcess/runtests.jl, test/Localizers/runtests.jl, test/SparseInversion/runtests.jl
Closes #287 
- more consistent plotting between tests
- adjustments to the test problems
- removed inappropriate Localization tests in `EnsembleKalmanProcess/runtests.jl` examples, (they are already properly tested in `Localizers/runtests.jl` ) - These caused blow up without disturbing the ensemble mean, therefore added some spread-checking too to ensure the tr(ensemble cov) does not increase too much
- test UKI with nonlinear problems, not just linear ones
- Added prior Tikhonov regularization for UKI, modified test checks to account for the regularization.
- Changed the default `update_freq` in UKI from 1 to 0. I.e. uses prior cov not current cov by default.
- Minor type change in UKI constructor to allow arrays to be converted to float type internally
- added note to docs RE this …
=> [WIP] Resolving some test problem consistency and apparent UKI instability

src/EnsembleKalmanProcess.jl
Fixed a typo in the docstring
----
- [x ] I have read and checked the items on the review checklist.
=> minor typo fix for docstring of get_ϕ

docs/src/parameter_distributions.md, src/ParameterDistributions.jl, test/ParameterDistributions/runtests.jl
Fixes #300 
Addresses GRF docs part of #282 
NB this is merely documenting what is currently implemented, improvements to the API will come soon.
- Adds the `constraint` keyword to fix `base.show()` bug with function distributions
- runs `show(parameter_distribution)` during tests to appease codecov
- Adds a section  and example of creating and plotting `GaussianRandomFieldInterface` object and samples.
Relevant docs section found [here](https://clima.github.io/EnsembleKalmanProcesses.jl/previews/PR304/parameter_distributions/#FunctionParameterDistributionType) and [here](https://clima.github.io/EnsembleKalmanProcesses.jl/previews/PR304/parameter_distributions/#function-example).
----
=> Function parameter documentation

examples/Sinusoid/sinusoid_example.jl
The prior has a standard deviation of 5, so the variance is 25. However, I accidentally wrote down a variance of 5 in the documentation.
=> Fixing small error in example documentation

src/LearningRateSchedulers.jl
The `history` field in DataMisfitController no longer does anything. It should be removed.
=> Removing unused `history` field in DataMisfitController

docs/src/API/EnsembleKalmanProcess.md, docs/src/learning_rate_scheduler.md, docs/src/parameter_distributions.md, src/LearningRateSchedulers.jl
Closes #311 
Closes #308 
----
=> Small docs updates

src/ParameterDistributions.jl
=> Fast concatentation

src/EnsembleKalmanProcess.jl, src/EnsembleTransformKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl
I somehow made some mistake with the branches and closed the last PR, #320, and couldn't reopen it. This should be ready to merge. Closes #324.
For Julia v1 tests outputs:
```
ETKI with 10 observations took 0.013366613000000005 seconds.
ETKI with 100 observations took 0.026825424999999983 seconds.
ETKI with 1000 observations took 0.17781986400000005 seconds.
ETKI with 10000 observations took 1.249208766 seconds.
```
=> Ensemble tranform Kalman inversion

src/Accelerators.jl, src/EnsembleKalmanProcess.jl, src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl
Closes #333
- Adds the accelerator method to `Unscented`. This implementation moves the sigma points (as it is the "ensemble") and then saves the reconstructed the mean and covariance from the new sigma point locations. Note one additional subtlety, the saved "u_mean" and "uu_cov" are not just the mean and cov of the sigma points, and so are back calculated
- Adds unit tests & removed some unnecessary ensemble members / iterations in the accelerator test
- renames the ambiguous `update_state!` to `accelerate!`
```
Accelerator: DefaultAccelerator Process: Inversion
┌ Info: Convergence:
│   cost_initial = 48.24023862169107
└   cost_final = 4.489933318021739
Accelerator: NesterovAccelerator Process: Inversion
┌ Info: Convergence:
│   cost_initial = 48.24023862169107
└   cost_final = …
```
=> Unscented accelerator 

src/LearningRateSchedulers.jl, test/EnsembleKalmanProcess/runtests.jl
`posdef_correct` was modifying inputs in-place due to the for loop over diagonal elements in the symmetric matrix case. This resulted in the DMC scheduler directly modifying the EKP obs_noise_cov matrix in the first iteration. This PR:
1. Uses deepcopy to prevent in-place modification of the EKP obs_noise_cov and modify tests to detect this.
2. Exports `posdef_correct` for external use.
Note: examples/LearningRateSchedulers is using `UniformScaling` and remains unaffected.
=> Prevent DataMisfitController scheduler from modifying EKP obs_noise_cov

docs/src/ensemble_kalman_inversion.md
=> Documentation for ETKI

bors.toml, src/Accelerators.jl, src/EnsembleKalmanProcess.jl, src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl
- closes #339
- changes the momentum parameter from $\beta_k = \frac{2}{k+2}$ into  $\beta_k = \theta_k(\theta_{k-1}^{-1} - 1)$ with $\theta_{0} = 1$. The new general formulation always satisfies a required quadratic inequality needed for convergence acceleration proofs. Explicitly, one picks $\theta_k$ to satisfy $\frac{1-\theta_k}{\theta_k^2}\Delta t_k \leq \frac{\Delta t_{k-1}}{\theta_{k-1}^2}$. 
- small UKI bug-fix (just stops some warnings on compile)
- moved the original `NesterovAccelerator` to `ConstantStepNesterovAccelerator`
- added 1 hr to bors timer, mac OS tests are being 10x slower today than yesterday (with no changes on our end)
Runs additional tests with 20 steps of the `DataMisfitController()` learning rate scheduler. Preliminary findings
- It seems even for constant …
=> modified accelerator for variable timestep

src/TOMLInterface.jl, test/TOMLInterface/runtests.jl, test/TOMLInterface/toml/bad_param.toml, test/TOMLInterface/toml/uq_test_parameters.toml
A few notes:
- The test for this parser directly compares to a `Parameterized(Normal())` distribution rather than the `constrained_gaussian` constructor
- If the distribution being parsed is a constrained gaussian, the constraint constructor is bypassed
=> Add `constrained_gaussian` TOML parser

src/TOMLInterface.jl
This is intended to address #354
=> Remove `getfield(Main, ...)`

examples/Accelerators/DarcyAccelerated/darcy_accelerated.jl, examples/Accelerators/ExpSinAccelerated/exp_sinusoid_accelerated.jl, examples/Accelerators/LorenzAccelerated/lorenz_accelerated.jl, src/Accelerators.jl, test/EnsembleKalmanProcess/runtests.jl
- removal of explicit timestep dependency of `NesterovAccelerator()` appears to be a more robust approach with a do-no-harm adjustment
- removal of `Delta t` and `Delta t_prev` dependency
- add fig_save directories and fig_save naming based on timestep for accelerated examples. 
- add some info statements, more encapsulated "cases", (i) constant stepper, (ii) dmc stepper (iii) dmc with localization and small ensemble (size = 5)
- Add GC into Darcy example over random trials.
- Added simple `ConstantNesterovAccelerator` which sets the momentum parameter = constant
- Renamed `ConstantStepNesterovAccelerator` to `FirstOrderNesterovAccelerator`
- Fixed an off-by-one error in `FirstOrder`
- **KEY INSIGHT:** Acceleration still proves to have increased benefit for small ensembles while using …
=> Updated accelerators with variable timestep, add localization case to examples

docs/src/examples/darcy.md
"Permeability" was spelled wrong.
=> Fix a typo in `darcy.md`

docs/src/inflation.md, src/EnsembleKalmanInversion.jl, src/EnsembleKalmanProcess.jl, src/EnsembleKalmanSampler.jl, src/EnsembleTransformKalmanInversion.jl, src/LearningRateSchedulers.jl, src/SparseEnsembleKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl, test/Inflation/runtests.jl, test/SparseInversion/runtests.jl
Closes #359
- Change all `MvNormal(m,C)` to `m .+ sqrt(C) * MvNormal(0,I)`, which can handle semi-definite "C"
- bugfix: Add `rng` into sample_empirical_gaussian
- Remove DMC test for Sparse inversion as it no longer seems to converge. _I believe this was likely unstable even in previous version of the code, stick with constant timesteppers_
-  allow users to provide an additive inflation matrix, defaults to prior covariance. `additive_inflation_cov = ...` in update to provide this. This allows for users to break the subspace property
- Unit tests for the new interface
- updated the inflation docs page [here](https://clima.github.io/EnsembleKalmanProcesses.jl/previews/PR360/inflation/)
E.g in `Examples/LorenzAccelerated/lorenz_accelerated.jl`,  on `main` the following breaks
```julia …
```
=> remove positive definiteness constraints, allow user defined additive inflation

src/TOMLInterface.jl, test/Project.toml, test/TOMLInterface/runtests.jl
This adds a function `save_parameter_samples` which takes samples from the given Samples distribution and saves them to individual TOML files for use in model runs.
=> Add `save_parameter_samples`

Project.toml, src/EnsembleKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl
Closes #389 
& Bump to 1.1.7
- add a repeat call to build a matrix of repeated observations
- add a call to `deterministic_forward_map = false` in unit tests to catch errors like this in future
----
=> Bump version to v1.1.7 after bugfix

examples/Accelerators/DarcyAccelerated/darcy_accelerated.jl, examples/Accelerators/DarcyAccelerated/darcy_singletrial.jl, examples/Accelerators/ExpSinAccelerated/exp_sinusoid_accelerated.jl, examples/Accelerators/LorenzAccelerated/lorenz_accelerated.jl, src/EnsembleKalmanInversion.jl
Closes #396
- bug-fix `N_ens` overwrite in Darcy example
- add `accelerator=DefaultAccelerator()` in all "vanilla" configurations in the accelerator examples
- remove `deterministic_forward_map` flags for accelerator as it is overwritten as `false`
- change `deterministic_forward_map=false` in non-accelerated methods for fair comparison
- added warning about the internal change for acceleration if unexpected for user
- ExpSin   (vanilla EKI no-longer accelerated in plot)
----
=> updated accelerator examples

.github/workflows/Tests.yml, README.md, test/EnsembleKalmanProcess/runtests.jl, test/ParameterDistributions/runtests.jl, test/TOMLInterface/runtests.jl
Updates workflows and CI:
- removes x64 architecture constraint
- Julia v1.11 changes (entirely required due to changing RNG)
- update 1.6 to LTS
- tests now pass
- updated workflow github-actions
- MacOS gives stackoverflow during 10,000 obs computation with ETKI - this is not present in any other OS or on v1.11 versions so will be ignored. Possibly it arises during `inv` calculations - BLAS has been known to cause such errors for large matrices
----
=> Remove arch bugfix for MacOS CI

src/Observations.jl
Otherwise we can get a StackOverflow error with large `samples`, eg
```julia
ERROR: LoadError: StackOverflowError:
Stacktrace:
[1] promote_type(::Type, ::Type, ::Type, ::Type, ::Vararg{Type}) (repeats 600 times)
@ Base ./promotion.jl:299
[2] Observation(obs_dict::Dict{String, Any})
@ EnsembleKalmanProcesses ~/.julia/packages/EnsembleKalmanProcesses/hifDM/src/Observations.jl:125
[3] include(fname::String)
@ Base.MainInclude ./client.jl:489
```
(And this may only be an issue on mac!)
=> Use `eltype` instead of `promote_type`

.github/workflows/Tests.yml, docs/make.jl, docs/src/update_groups.md, examples/Localization/localization_example_lorenz96.jl, examples/UpdateGroups/Project.toml, examples/UpdateGroups/calibrate.jl, examples/UpdateGroups/data_processing.jl, examples/UpdateGroups/lorenz_model.jl, examples/UpdateGroups/plot_covs.jl, src/EnsembleKalmanInversion.jl, src/EnsembleKalmanProcess.jl, src/EnsembleKalmanProcesses.jl, src/EnsembleKalmanSampler.jl, src/EnsembleTransformKalmanInversion.jl, src/GaussNewtonKalmanInversion.jl, src/Localizers.jl, src/SparseEnsembleKalmanInversion.jl, src/UnscentedKalmanInversion.jl, src/UpdateGroup.jl, test/Inflation/runtests.jl, test/Localizers/runtests.jl, test/UpdateGroup/runtests.jl, test/runtests.jl
Closes #377
Indirectly, Closes #288 
To review the PR and see what is going on I would suggest, 
- playing with the `example/UpdateGroups/calibrate.jl`.
- Looking at the `src/UpdateGroups.jl` file
- Looking at `src/EnsembleKalmanProcess.jl` function `update_ensemble!(...)`
- look at the docs page ["Update Groups"](https://clima.github.io/EnsembleKalmanProcesses.jl/previews/PR380/update_groups/)
- `UpdateGroup` object
- unit tests for `UpdateGroup`
- implemented an interface with all EKP methods, in  particular this necessitated  lifting saving of "g", and verbose flag statements out of the individual updates thus reducing a lot of duplicated code
- implemented functionality for EKI
- Constructed an example based on learning "fast" and "slow" parameters of a coupled L96 model, hopefully …
=> Update groups, i.e. domain and observation localization

src/ParameterDistributions.jl, test/ParameterDistributions/runtests.jl
Closes #454
- found an additional "-" in the definition (which was not even consistent with docstring). so it should do `up bound - exp(x)` not `up bound - exp(-x)` and vice versa.
- modified an incorrect unit test that hid the bug
```
using Statistics, EnsembleKalmanProcesses
using EnsembleKalmanProcesses.ParameterDistributions
prior = constrained_gaussian("neg",-5,1,-Inf,0)
prior2 = constrained_gaussian("pos",5,1,0,Inf)
```
Then 
```
julia> mean(transform_unconstrained_to_constrained(prior, sample(prior,10000)))
-5.006444836517459
julia> std(transform_unconstrained_to_constrained(prior, sample(prior,10000)))
1.0009663702218747
julia> mean(transform_unconstrained_to_constrained(prior2, sample(prior2,10000)))
4.999637758663166
julia> std(transform_unconstrained_to_constrained(prior2, …
```
=> Bugfix for bounded above distributions

src/LearningRateSchedulers.jl, test/EnsembleKalmanProcess/runtests.jl
- Closes #461 
- Compute the potential in DMC using `get_obs_noise_cov_inv(ekp, build=false)` rather than `get_obs_noise_cov(ekp)` and so avoiding building the full inverse
- remove the stored `sqrt_inv_\Gamma` previously required (as recently we now store the inverses in reduced form in EKP)
- Add `DataMisfitController()` as the scheduler for the ETKI scaling unit-test
----
=> Improve DMC scheduler scaling with large observation dimension

docs/src/API/EnsembleKalmanProcess.md, src/EnsembleKalmanProcess.jl, test/EnsembleKalmanProcess/runtests.jl
Closes #460 
- introduced nan preprocessing in line with issue #460
- added unit tests
- when ekp.verbose = true, produce details of NaNs found. false provides less information RE failed NaN rows, and # imputed values
- Allow users to define their fixed vector of values `nan_row_values` as a sensible replacement if they prefer alternate behaviour
Take a matrix `g`
```
g 
7×4 Matrix{Float64}:
NaN           0.992373   NaN           -0.200025
-1.37133     0.0527899  NaN           -1.15243
NaN         NaN          NaN          NaN
NaN         NaN          NaN          NaN
-2.28799   NaN            0.614214     1.54217
0.582582    0.0744582   -1.37219      0.253971
0.620447    0.441834     0.0641471    0.490588
```
with `nan_tolerance = 0.5`, `nan_row_vals = collect(1:7)`, and then the …
=> New Quantification of member failure, and more flexible NaN handling

Project.toml, docs/src/API/Observations.md, src/EnsembleKalmanProcess.jl, src/EnsembleTransformKalmanInversion.jl, src/LearningRateSchedulers.jl, src/Observations.jl, test/EnsembleKalmanProcess/runtests.jl, test/Observations/runtests.jl
- Closes #452
- Add function `tsvd_mat(X, r,...)` to create SVD objects representing rank `r` approximation of `X` (and optionally its pseudoinverse)
- Add `tsvd_cov_from_samples` function to aid in computing the SVD of `cov(X,dims=2)` from a sample matrix `X`. (rank and return of pseudoinverse can be specified too)
- Add infrastructure for getting covariances via `build=false`, to ensure ETKI can work without disrupting scalability.
- Add unit test to ensure scaling remains modest. And extend test to run 2 iterations up to dim 1_000_000
- code infrastructure for algorithms that get covariances with `build = true` options (e.g. basic EKI) 
- new internal functions `lmul_obs_noise_cov_inv` and `lmul_obs_noise_cov_inv!` to wrap up the increasingly messy linear algebra.
Case 1: From a matrix …
=> Extend observations handle (T)SVD covariance objects efficiently

src/EnsembleKalmanProcess.jl, src/EnsembleTransformKalmanInversion.jl, src/Observations.jl, test/Observations/runtests.jl
- I noticed that the example `loss_minimization_finite_vs_infinite.jl` had changed behaviour from v2.2.0 to v2.3.0. This bug-fixes the indexing issue and clears-up and hides the logic to prevent future index errors.
**v2.3.0** results not comparable with PR #444 (see yellow dashed line - showing ETKI infinite ensemble not collapsing)
- index-shift error fixed, 
- replaced `onci_idx` logic 
- Bugfix prior not being pulled in lmul function. (manually apply prior after)
**New** results are now matching those of PR #444
----
=> ETKI (infinite-version) bugfixes and clarity of logic

Project.toml
This PR removes the implicit dependency on Plots.jl by using the newest GaussianRandomFields release.
```
(EnsembleKalmanProcesses) pkg> st GaussianRandomFields
Project EnsembleKalmanProcesses v2.4.0
Status `~/clima/EnsembleKalmanProcesses.jl/Project.toml`
[e4b2fa32] GaussianRandomFields v2.2.5
(EnsembleKalmanProcesses) pkg> why Plots
GaussianRandomFields → Plots
```
Strictly speaking, we don’t need to restrict compatibility, I could manually ensure that I am using GaussianRandomFields 2.2.6 in my workflow. However, I’d prefer to enforce this constraint to prevent Plots from accidentally becoming a dependency, which helps reduce compilation time.
----
=> Update GaussianRandomFields compat, remove Plots dependency

Project.toml, docs/src/API/EnsembleKalmanProcess.md, src/EnsembleKalmanProcess.jl, src/EnsembleKalmanSampler.jl, src/GaussNewtonKalmanInversion.jl, src/Observations.jl, src/SparseEnsembleKalmanInversion.jl, src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl, test/Observations/runtests.jl, test/SparseInversion/runtests.jl
Closes #483 
Closes #488
Also relates to the plotting in #476 
- Bugfix for producing NaNs when computing an error with NaN outputs (even with successful failure handling)
- Add new metrics, that are weighted by the dimension:
1. `compute_loss_at_mean` (current logic from `compute_error!` )
2. `compute_unweighted_loss_at_mean` (g_mean- y)' (g_mean - y)
3. `compute_average_rmse` (average of cov-weighted rmse taken across the ensemble)
4. `compute_average_unweighted_rmse` (average of unweighted rmse taken across the ensemble)
5. `compute_bayesian_loss_at_mean` (loss at mean + prior contribution (from provided prior or estimated from initial ensemble)
6. `compute_crps` (Gaussian-approximated continuous rank probability score for ensemble vs observation)
- UKI/UTKI variants have an equivalent …
=> compute_error! bugfix, and add some more error metrics

docs/src/API/EnsembleKalmanProcess.md, docs/src/API/Observations.md, src/EnsembleKalmanProcess.jl, src/Observations.jl, test/EnsembleKalmanProcess/runtests.jl, test/Observations/runtests.jl
Closes #487 
- added optional `iteration` in getters for observation (e.g., `get_obs(ekp, iteration)` ) also for `get_obs_noise_cov` and `get_obs_noise_cov_inv`
- added some utilities such as `get_minibatch_index(observation_series, iteration)` to also get observations from `iteration`
- added `get_algorithm_time` with accumulates the `get_[\Delta]t(ekp)`
- Unit tests and API docs
----
=> New getters for observations etc.

Project.toml, docs/Project.toml, docs/make.jl, docs/src/API/Visualize.md, docs/src/visualization.md, ext/EnsembleKalmanProcessesMakieExt.jl, src/EnsembleKalmanProcesses.jl, src/Visualize.jl, test/Visualize/runtests.jl, test/runtests.jl
This PR adds a Makie extension for plotting. This is still a work in progress.
The new docs page can be found [here](https://clima.github.io/EnsembleKalmanProcesses.jl/previews/PR482/visualization/)
Here are some plots that can be made so far.
=> Add Makie extension for plotting

docs/src/API/Observations.md, docs/src/observations.md, src/Observations.jl, test/Observations/runtests.jl
- Request from @nefrathenrici to extend the utility of `metadata` from `ObservationSeries` to individual `Observation` objects
- Add optional metadata object to `Observation`, set either with `metadata=...` or `Dict(...,"metadata" => ...)` when creating the `Observation`. It is value `nothing` when not set.
- metadata is stacked under `combine_observations([obs1,obs2])` and is retrieved with `get_metadata(observation)`
- API and additional note in docs provided
- unit tested
----
=> Add Metadata to `Observation` object

src/Observations.jl
- Closes #504 
- put `sqrt(N-1)` ->  `FT(sqrt(N- 1))` for inferred `FT` from eltype of input matrix
- replace `1.0 ./ A` with `1 ./ A`
```julia
import EnsembleKalmanProcesses as EKP
samples_mat = Float32.([[1, 2, 4, 6]  [3, 4, 4, 4]])
covv, inv_covv = EKP.tsvd_cov_from_samples(samples_mat, return_inverse=true)
eltype(covv.S) == Float32 # true
eltype(covv.U) == Float32 # true
eltype(covv.V) == Float32 # true
eltype(covv.Vt) == Float32 # true
eltype(inv_covv.S) == Float32 # true
eltype(inv_covv.U) == Float32 # true
eltype(inv_covv.V) == Float32 # true
eltype(inv_covv.Vt) == Float32 # true
```
----
=> tsvd_cov_from_samples - type stability

docs/src/API/EnsembleKalmanProcess.md, docs/src/API/Unscented.md, src/EnsembleKalmanProcess.jl, src/UnscentedKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl
Resolves #523 
- Add `construct_initial_ensemble(prior, unscented, constrained=false)` method to give the sigma ensemble of the initial ensemble in unscented (transform-unscented) processes
- Add the constrained flag to all methods of `construct_initial_ensemble(; constrained=false)` - false by default to maintain back compatability
----
=> Add convenience to construct UKI initial ensemble before creating EKP

src/EnsembleKalmanInversion.jl, src/EnsembleKalmanProcess.jl, src/EnsembleKalmanProcesses.jl, src/EnsembleKalmanSampler.jl, src/EnsembleTransformKalmanInversion.jl, src/GaussNewtonKalmanInversion.jl, src/LinearSolve.jl, src/ParameterDistributions.jl, src/SparseEnsembleKalmanInversion.jl, src/UnscentedKalmanInversion.jl, src/UnscentedTransformKalmanInversion.jl, test/EnsembleKalmanProcess/runtests.jl
Content 
- `safe_linear_solve(A,b)`: solves via `A\b` and falls back to `pinv(A)*b` on `SingularException`, with a warning that can be disabled
- `add_diagonal_regularization!(cov_matrix)`: Adds a `sqrt(eps(eltype(cov_matrix)))` to the input matrix's diagonal 
- Applies `add_diagonal_regularization!` and `safe_linear_solve` to the source code. I am not sure that I applied regularization everywhere it is needed.
=> Add fallback for linear solve
